name: Ping Supabase database to Prevent Pausing
##Need to add these secrets in your GitHub repository under Settings > Secrets and variables > Actions.

on:
  schedule:
    - cron: '0 9 * * 1,4' # Runs at 9:00 AM UTC every Monday and Thursday
  workflow_dispatch: #can be used to trigger the workflow manually on Github UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node -e '
          (async () => {
            try {
              const { createClient } = require("@supabase/supabase-js");
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

              // Query Bills table
              const { data, error } = await supabase.from("Bills").select("*").limit(1);

              if (error) throw error;

              console.log("Ping successful:", data);
            } catch (err) {
              console.error("Error pinging Supabase:", err.message);
              process.exit(1);
            }
          })();
          '
